/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : Id,
  'title' : string,
  'body' : string,
  'createdAt' : Timestamp,
  'pinned' : boolean,
}
export interface AnnouncementInput {
  'title' : string,
  'body' : string,
  'pinned' : boolean,
}
export interface BibleReading {
  'id' : Id,
  'createdAt' : Timestamp,
  'text' : string,
  'reference' : string,
  'isReadingOfDay' : boolean,
}
export interface BibleReadingInput { 'text' : string, 'reference' : string }
export interface Class {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'teacher' : string,
  'description' : string,
  'schedule' : string,
}
export interface ClassInput {
  'name' : string,
  'teacher' : string,
  'description' : string,
  'schedule' : string,
}
export type ExternalBlob = Uint8Array;
export interface Hymn {
  'id' : Id,
  'title' : string,
  'lyrics' : string,
  'createdAt' : Timestamp,
  'number' : bigint,
}
export interface HymnInput {
  'title' : string,
  'lyrics' : string,
  'number' : bigint,
}
export type Id = bigint;
export interface LectureMaterial {
  'id' : Id,
  'title' : string,
  'file' : ExternalBlob,
  'fileName' : string,
  'classId' : Id,
  'uploadedAt' : Timestamp,
}
export interface LectureMaterialInput {
  'title' : string,
  'file' : ExternalBlob,
  'fileName' : string,
  'classId' : Id,
}
export interface MensItem {
  'id' : Id,
  'title' : string,
  'date' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'description' : string,
  'leader' : string,
  'category' : string,
}
export interface MensItemInput {
  'title' : string,
  'date' : [] | [Timestamp],
  'description' : string,
  'leader' : string,
  'category' : string,
}
export interface MothersItem {
  'id' : Id,
  'title' : string,
  'date' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'description' : string,
  'leader' : string,
  'category' : string,
}
export interface MothersItemInput {
  'title' : string,
  'date' : [] | [Timestamp],
  'description' : string,
  'leader' : string,
  'category' : string,
}
export interface OfferingInfo {
  'bankAccount' : string,
  'mpesaName' : string,
  'instructions' : string,
  'bankName' : string,
  'mpesaNumber' : string,
  'bankBranch' : string,
}
export interface ProgramItem {
  'id' : Id,
  'order' : bigint,
  'createdAt' : Timestamp,
  'time' : string,
  'activity' : string,
}
export interface ProgramItemInput {
  'order' : bigint,
  'time' : string,
  'activity' : string,
}
export interface Sermon {
  'id' : Id,
  'preacher' : string,
  'theme' : string,
  'scriptureRef' : string,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : string,
}
export interface SermonInput {
  'preacher' : string,
  'theme' : string,
  'scriptureRef' : string,
  'date' : Timestamp,
  'notes' : string,
}
export interface ServiceBookItem {
  'id' : Id,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'step' : bigint,
}
export interface ServiceBookItemInput {
  'title' : string,
  'content' : string,
  'step' : bigint,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YouthItem {
  'id' : Id,
  'title' : string,
  'date' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'description' : string,
  'leader' : string,
  'category' : string,
}
export interface YouthItemInput {
  'title' : string,
  'date' : [] | [Timestamp],
  'description' : string,
  'leader' : string,
  'category' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAnnouncement' : ActorMethod<[AnnouncementInput], Announcement>,
  'addBibleReading' : ActorMethod<[BibleReadingInput], BibleReading>,
  'addClass' : ActorMethod<[ClassInput], Class>,
  'addHymn' : ActorMethod<[HymnInput], Hymn>,
  'addLectureMaterial' : ActorMethod<[LectureMaterialInput], LectureMaterial>,
  'addMensItem' : ActorMethod<[MensItemInput], MensItem>,
  'addMothersItem' : ActorMethod<[MothersItemInput], MothersItem>,
  'addProgramItem' : ActorMethod<[ProgramItemInput], ProgramItem>,
  'addSermon' : ActorMethod<[SermonInput], Sermon>,
  'addServiceBookItem' : ActorMethod<[ServiceBookItemInput], ServiceBookItem>,
  'addYouthItem' : ActorMethod<[YouthItemInput], YouthItem>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAnnouncement' : ActorMethod<[Id], boolean>,
  'deleteBibleReading' : ActorMethod<[Id], boolean>,
  'deleteClass' : ActorMethod<[Id], boolean>,
  'deleteHymn' : ActorMethod<[Id], boolean>,
  'deleteLectureMaterial' : ActorMethod<[Id], boolean>,
  'deleteMensItem' : ActorMethod<[Id], boolean>,
  'deleteMothersItem' : ActorMethod<[Id], boolean>,
  'deleteProgramItem' : ActorMethod<[Id], boolean>,
  'deleteSermon' : ActorMethod<[Id], boolean>,
  'deleteServiceBookItem' : ActorMethod<[Id], boolean>,
  'deleteYouthItem' : ActorMethod<[Id], boolean>,
  'getAnnouncement' : ActorMethod<[Id], [] | [Announcement]>,
  'getBibleReading' : ActorMethod<[Id], [] | [BibleReading]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[Id], [] | [Class]>,
  'getHymn' : ActorMethod<[Id], [] | [Hymn]>,
  'getMensItem' : ActorMethod<[Id], [] | [MensItem]>,
  'getMothersItem' : ActorMethod<[Id], [] | [MothersItem]>,
  'getOfferingInfo' : ActorMethod<[], [] | [OfferingInfo]>,
  'getProgramItem' : ActorMethod<[Id], [] | [ProgramItem]>,
  'getSermon' : ActorMethod<[Id], [] | [Sermon]>,
  'getYouthItem' : ActorMethod<[Id], [] | [YouthItem]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'listBibleReadings' : ActorMethod<[], Array<BibleReading>>,
  'listClasses' : ActorMethod<[], Array<Class>>,
  'listHymns' : ActorMethod<[], Array<Hymn>>,
  'listLectureMaterials' : ActorMethod<[Id], Array<LectureMaterial>>,
  'listMensItems' : ActorMethod<[], Array<MensItem>>,
  'listMothersItems' : ActorMethod<[], Array<MothersItem>>,
  'listProgramItems' : ActorMethod<[], Array<ProgramItem>>,
  'listSermons' : ActorMethod<[], Array<Sermon>>,
  'listServiceBookItems' : ActorMethod<[], Array<ServiceBookItem>>,
  'listYouthItems' : ActorMethod<[], Array<YouthItem>>,
  'searchHymns' : ActorMethod<[string], Array<Hymn>>,
  'setReadingOfDay' : ActorMethod<[Id], boolean>,
  'updateAnnouncement' : ActorMethod<
    [Id, AnnouncementInput],
    [] | [Announcement]
  >,
  'updateBibleReading' : ActorMethod<
    [Id, BibleReadingInput],
    [] | [BibleReading]
  >,
  'updateClass' : ActorMethod<[Id, ClassInput], [] | [Class]>,
  'updateHymn' : ActorMethod<[Id, HymnInput], [] | [Hymn]>,
  'updateMensItem' : ActorMethod<[Id, MensItemInput], [] | [MensItem]>,
  'updateMothersItem' : ActorMethod<[Id, MothersItemInput], [] | [MothersItem]>,
  'updateOfferingInfo' : ActorMethod<[OfferingInfo], undefined>,
  'updateProgramItem' : ActorMethod<[Id, ProgramItemInput], [] | [ProgramItem]>,
  'updateSermon' : ActorMethod<[Id, SermonInput], [] | [Sermon]>,
  'updateServiceBookItem' : ActorMethod<
    [Id, ServiceBookItemInput],
    [] | [ServiceBookItem]
  >,
  'updateYouthItem' : ActorMethod<[Id, YouthItemInput], [] | [YouthItem]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];