/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AnnouncementInput = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'pinned' : IDL.Bool,
});
export const Id = IDL.Nat;
export const Timestamp = IDL.Int;
export const Announcement = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'pinned' : IDL.Bool,
});
export const BibleReadingInput = IDL.Record({
  'text' : IDL.Text,
  'reference' : IDL.Text,
});
export const BibleReading = IDL.Record({
  'id' : Id,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'reference' : IDL.Text,
  'isReadingOfDay' : IDL.Bool,
});
export const ClassInput = IDL.Record({
  'name' : IDL.Text,
  'teacher' : IDL.Text,
  'description' : IDL.Text,
  'schedule' : IDL.Text,
});
export const Class = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'teacher' : IDL.Text,
  'description' : IDL.Text,
  'schedule' : IDL.Text,
});
export const HymnInput = IDL.Record({
  'title' : IDL.Text,
  'lyrics' : IDL.Text,
  'number' : IDL.Nat,
});
export const Hymn = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'lyrics' : IDL.Text,
  'createdAt' : Timestamp,
  'number' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LectureMaterialInput = IDL.Record({
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'fileName' : IDL.Text,
  'classId' : Id,
});
export const LectureMaterial = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'fileName' : IDL.Text,
  'classId' : Id,
  'uploadedAt' : Timestamp,
});
export const MensItemInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'leader' : IDL.Text,
  'category' : IDL.Text,
});
export const MensItem = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'date' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'leader' : IDL.Text,
  'category' : IDL.Text,
});
export const MothersItemInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'leader' : IDL.Text,
  'category' : IDL.Text,
});
export const MothersItem = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'date' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'leader' : IDL.Text,
  'category' : IDL.Text,
});
export const ProgramItemInput = IDL.Record({
  'order' : IDL.Nat,
  'time' : IDL.Text,
  'activity' : IDL.Text,
});
export const ProgramItem = IDL.Record({
  'id' : Id,
  'order' : IDL.Nat,
  'createdAt' : Timestamp,
  'time' : IDL.Text,
  'activity' : IDL.Text,
});
export const SermonInput = IDL.Record({
  'preacher' : IDL.Text,
  'theme' : IDL.Text,
  'scriptureRef' : IDL.Text,
  'date' : Timestamp,
  'notes' : IDL.Text,
});
export const Sermon = IDL.Record({
  'id' : Id,
  'preacher' : IDL.Text,
  'theme' : IDL.Text,
  'scriptureRef' : IDL.Text,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : IDL.Text,
});
export const ServiceBookItemInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'step' : IDL.Nat,
});
export const ServiceBookItem = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'step' : IDL.Nat,
});
export const YouthItemInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'leader' : IDL.Text,
  'category' : IDL.Text,
});
export const YouthItem = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'date' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'leader' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OfferingInfo = IDL.Record({
  'bankAccount' : IDL.Text,
  'mpesaName' : IDL.Text,
  'instructions' : IDL.Text,
  'bankName' : IDL.Text,
  'mpesaNumber' : IDL.Text,
  'bankBranch' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAnnouncement' : IDL.Func([AnnouncementInput], [Announcement], []),
  'addBibleReading' : IDL.Func([BibleReadingInput], [BibleReading], []),
  'addClass' : IDL.Func([ClassInput], [Class], []),
  'addHymn' : IDL.Func([HymnInput], [Hymn], []),
  'addLectureMaterial' : IDL.Func(
      [LectureMaterialInput],
      [LectureMaterial],
      [],
    ),
  'addMensItem' : IDL.Func([MensItemInput], [MensItem], []),
  'addMothersItem' : IDL.Func([MothersItemInput], [MothersItem], []),
  'addProgramItem' : IDL.Func([ProgramItemInput], [ProgramItem], []),
  'addSermon' : IDL.Func([SermonInput], [Sermon], []),
  'addServiceBookItem' : IDL.Func(
      [ServiceBookItemInput],
      [ServiceBookItem],
      [],
    ),
  'addYouthItem' : IDL.Func([YouthItemInput], [YouthItem], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnnouncement' : IDL.Func([Id], [IDL.Bool], []),
  'deleteBibleReading' : IDL.Func([Id], [IDL.Bool], []),
  'deleteClass' : IDL.Func([Id], [IDL.Bool], []),
  'deleteHymn' : IDL.Func([Id], [IDL.Bool], []),
  'deleteLectureMaterial' : IDL.Func([Id], [IDL.Bool], []),
  'deleteMensItem' : IDL.Func([Id], [IDL.Bool], []),
  'deleteMothersItem' : IDL.Func([Id], [IDL.Bool], []),
  'deleteProgramItem' : IDL.Func([Id], [IDL.Bool], []),
  'deleteSermon' : IDL.Func([Id], [IDL.Bool], []),
  'deleteServiceBookItem' : IDL.Func([Id], [IDL.Bool], []),
  'deleteYouthItem' : IDL.Func([Id], [IDL.Bool], []),
  'getAnnouncement' : IDL.Func([Id], [IDL.Opt(Announcement)], ['query']),
  'getBibleReading' : IDL.Func([Id], [IDL.Opt(BibleReading)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([Id], [IDL.Opt(Class)], ['query']),
  'getHymn' : IDL.Func([Id], [IDL.Opt(Hymn)], ['query']),
  'getMensItem' : IDL.Func([Id], [IDL.Opt(MensItem)], ['query']),
  'getMothersItem' : IDL.Func([Id], [IDL.Opt(MothersItem)], ['query']),
  'getOfferingInfo' : IDL.Func([], [IDL.Opt(OfferingInfo)], ['query']),
  'getProgramItem' : IDL.Func([Id], [IDL.Opt(ProgramItem)], ['query']),
  'getSermon' : IDL.Func([Id], [IDL.Opt(Sermon)], ['query']),
  'getYouthItem' : IDL.Func([Id], [IDL.Opt(YouthItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'listBibleReadings' : IDL.Func([], [IDL.Vec(BibleReading)], ['query']),
  'listClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'listHymns' : IDL.Func([], [IDL.Vec(Hymn)], ['query']),
  'listLectureMaterials' : IDL.Func(
      [Id],
      [IDL.Vec(LectureMaterial)],
      ['query'],
    ),
  'listMensItems' : IDL.Func([], [IDL.Vec(MensItem)], ['query']),
  'listMothersItems' : IDL.Func([], [IDL.Vec(MothersItem)], ['query']),
  'listProgramItems' : IDL.Func([], [IDL.Vec(ProgramItem)], ['query']),
  'listSermons' : IDL.Func([], [IDL.Vec(Sermon)], ['query']),
  'listServiceBookItems' : IDL.Func([], [IDL.Vec(ServiceBookItem)], ['query']),
  'listYouthItems' : IDL.Func([], [IDL.Vec(YouthItem)], ['query']),
  'searchHymns' : IDL.Func([IDL.Text], [IDL.Vec(Hymn)], ['query']),
  'setReadingOfDay' : IDL.Func([Id], [IDL.Bool], []),
  'updateAnnouncement' : IDL.Func(
      [Id, AnnouncementInput],
      [IDL.Opt(Announcement)],
      [],
    ),
  'updateBibleReading' : IDL.Func(
      [Id, BibleReadingInput],
      [IDL.Opt(BibleReading)],
      [],
    ),
  'updateClass' : IDL.Func([Id, ClassInput], [IDL.Opt(Class)], []),
  'updateHymn' : IDL.Func([Id, HymnInput], [IDL.Opt(Hymn)], []),
  'updateMensItem' : IDL.Func([Id, MensItemInput], [IDL.Opt(MensItem)], []),
  'updateMothersItem' : IDL.Func(
      [Id, MothersItemInput],
      [IDL.Opt(MothersItem)],
      [],
    ),
  'updateOfferingInfo' : IDL.Func([OfferingInfo], [], []),
  'updateProgramItem' : IDL.Func(
      [Id, ProgramItemInput],
      [IDL.Opt(ProgramItem)],
      [],
    ),
  'updateSermon' : IDL.Func([Id, SermonInput], [IDL.Opt(Sermon)], []),
  'updateServiceBookItem' : IDL.Func(
      [Id, ServiceBookItemInput],
      [IDL.Opt(ServiceBookItem)],
      [],
    ),
  'updateYouthItem' : IDL.Func([Id, YouthItemInput], [IDL.Opt(YouthItem)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AnnouncementInput = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'pinned' : IDL.Bool,
  });
  const Id = IDL.Nat;
  const Timestamp = IDL.Int;
  const Announcement = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'pinned' : IDL.Bool,
  });
  const BibleReadingInput = IDL.Record({
    'text' : IDL.Text,
    'reference' : IDL.Text,
  });
  const BibleReading = IDL.Record({
    'id' : Id,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'reference' : IDL.Text,
    'isReadingOfDay' : IDL.Bool,
  });
  const ClassInput = IDL.Record({
    'name' : IDL.Text,
    'teacher' : IDL.Text,
    'description' : IDL.Text,
    'schedule' : IDL.Text,
  });
  const Class = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'teacher' : IDL.Text,
    'description' : IDL.Text,
    'schedule' : IDL.Text,
  });
  const HymnInput = IDL.Record({
    'title' : IDL.Text,
    'lyrics' : IDL.Text,
    'number' : IDL.Nat,
  });
  const Hymn = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'lyrics' : IDL.Text,
    'createdAt' : Timestamp,
    'number' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LectureMaterialInput = IDL.Record({
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'fileName' : IDL.Text,
    'classId' : Id,
  });
  const LectureMaterial = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'fileName' : IDL.Text,
    'classId' : Id,
    'uploadedAt' : Timestamp,
  });
  const MensItemInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'leader' : IDL.Text,
    'category' : IDL.Text,
  });
  const MensItem = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'date' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'leader' : IDL.Text,
    'category' : IDL.Text,
  });
  const MothersItemInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'leader' : IDL.Text,
    'category' : IDL.Text,
  });
  const MothersItem = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'date' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'leader' : IDL.Text,
    'category' : IDL.Text,
  });
  const ProgramItemInput = IDL.Record({
    'order' : IDL.Nat,
    'time' : IDL.Text,
    'activity' : IDL.Text,
  });
  const ProgramItem = IDL.Record({
    'id' : Id,
    'order' : IDL.Nat,
    'createdAt' : Timestamp,
    'time' : IDL.Text,
    'activity' : IDL.Text,
  });
  const SermonInput = IDL.Record({
    'preacher' : IDL.Text,
    'theme' : IDL.Text,
    'scriptureRef' : IDL.Text,
    'date' : Timestamp,
    'notes' : IDL.Text,
  });
  const Sermon = IDL.Record({
    'id' : Id,
    'preacher' : IDL.Text,
    'theme' : IDL.Text,
    'scriptureRef' : IDL.Text,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'notes' : IDL.Text,
  });
  const ServiceBookItemInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'step' : IDL.Nat,
  });
  const ServiceBookItem = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'step' : IDL.Nat,
  });
  const YouthItemInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'leader' : IDL.Text,
    'category' : IDL.Text,
  });
  const YouthItem = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'date' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'leader' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OfferingInfo = IDL.Record({
    'bankAccount' : IDL.Text,
    'mpesaName' : IDL.Text,
    'instructions' : IDL.Text,
    'bankName' : IDL.Text,
    'mpesaNumber' : IDL.Text,
    'bankBranch' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAnnouncement' : IDL.Func([AnnouncementInput], [Announcement], []),
    'addBibleReading' : IDL.Func([BibleReadingInput], [BibleReading], []),
    'addClass' : IDL.Func([ClassInput], [Class], []),
    'addHymn' : IDL.Func([HymnInput], [Hymn], []),
    'addLectureMaterial' : IDL.Func(
        [LectureMaterialInput],
        [LectureMaterial],
        [],
      ),
    'addMensItem' : IDL.Func([MensItemInput], [MensItem], []),
    'addMothersItem' : IDL.Func([MothersItemInput], [MothersItem], []),
    'addProgramItem' : IDL.Func([ProgramItemInput], [ProgramItem], []),
    'addSermon' : IDL.Func([SermonInput], [Sermon], []),
    'addServiceBookItem' : IDL.Func(
        [ServiceBookItemInput],
        [ServiceBookItem],
        [],
      ),
    'addYouthItem' : IDL.Func([YouthItemInput], [YouthItem], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnnouncement' : IDL.Func([Id], [IDL.Bool], []),
    'deleteBibleReading' : IDL.Func([Id], [IDL.Bool], []),
    'deleteClass' : IDL.Func([Id], [IDL.Bool], []),
    'deleteHymn' : IDL.Func([Id], [IDL.Bool], []),
    'deleteLectureMaterial' : IDL.Func([Id], [IDL.Bool], []),
    'deleteMensItem' : IDL.Func([Id], [IDL.Bool], []),
    'deleteMothersItem' : IDL.Func([Id], [IDL.Bool], []),
    'deleteProgramItem' : IDL.Func([Id], [IDL.Bool], []),
    'deleteSermon' : IDL.Func([Id], [IDL.Bool], []),
    'deleteServiceBookItem' : IDL.Func([Id], [IDL.Bool], []),
    'deleteYouthItem' : IDL.Func([Id], [IDL.Bool], []),
    'getAnnouncement' : IDL.Func([Id], [IDL.Opt(Announcement)], ['query']),
    'getBibleReading' : IDL.Func([Id], [IDL.Opt(BibleReading)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([Id], [IDL.Opt(Class)], ['query']),
    'getHymn' : IDL.Func([Id], [IDL.Opt(Hymn)], ['query']),
    'getMensItem' : IDL.Func([Id], [IDL.Opt(MensItem)], ['query']),
    'getMothersItem' : IDL.Func([Id], [IDL.Opt(MothersItem)], ['query']),
    'getOfferingInfo' : IDL.Func([], [IDL.Opt(OfferingInfo)], ['query']),
    'getProgramItem' : IDL.Func([Id], [IDL.Opt(ProgramItem)], ['query']),
    'getSermon' : IDL.Func([Id], [IDL.Opt(Sermon)], ['query']),
    'getYouthItem' : IDL.Func([Id], [IDL.Opt(YouthItem)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'listBibleReadings' : IDL.Func([], [IDL.Vec(BibleReading)], ['query']),
    'listClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'listHymns' : IDL.Func([], [IDL.Vec(Hymn)], ['query']),
    'listLectureMaterials' : IDL.Func(
        [Id],
        [IDL.Vec(LectureMaterial)],
        ['query'],
      ),
    'listMensItems' : IDL.Func([], [IDL.Vec(MensItem)], ['query']),
    'listMothersItems' : IDL.Func([], [IDL.Vec(MothersItem)], ['query']),
    'listProgramItems' : IDL.Func([], [IDL.Vec(ProgramItem)], ['query']),
    'listSermons' : IDL.Func([], [IDL.Vec(Sermon)], ['query']),
    'listServiceBookItems' : IDL.Func(
        [],
        [IDL.Vec(ServiceBookItem)],
        ['query'],
      ),
    'listYouthItems' : IDL.Func([], [IDL.Vec(YouthItem)], ['query']),
    'searchHymns' : IDL.Func([IDL.Text], [IDL.Vec(Hymn)], ['query']),
    'setReadingOfDay' : IDL.Func([Id], [IDL.Bool], []),
    'updateAnnouncement' : IDL.Func(
        [Id, AnnouncementInput],
        [IDL.Opt(Announcement)],
        [],
      ),
    'updateBibleReading' : IDL.Func(
        [Id, BibleReadingInput],
        [IDL.Opt(BibleReading)],
        [],
      ),
    'updateClass' : IDL.Func([Id, ClassInput], [IDL.Opt(Class)], []),
    'updateHymn' : IDL.Func([Id, HymnInput], [IDL.Opt(Hymn)], []),
    'updateMensItem' : IDL.Func([Id, MensItemInput], [IDL.Opt(MensItem)], []),
    'updateMothersItem' : IDL.Func(
        [Id, MothersItemInput],
        [IDL.Opt(MothersItem)],
        [],
      ),
    'updateOfferingInfo' : IDL.Func([OfferingInfo], [], []),
    'updateProgramItem' : IDL.Func(
        [Id, ProgramItemInput],
        [IDL.Opt(ProgramItem)],
        [],
      ),
    'updateSermon' : IDL.Func([Id, SermonInput], [IDL.Opt(Sermon)], []),
    'updateServiceBookItem' : IDL.Func(
        [Id, ServiceBookItemInput],
        [IDL.Opt(ServiceBookItem)],
        [],
      ),
    'updateYouthItem' : IDL.Func(
        [Id, YouthItemInput],
        [IDL.Opt(YouthItem)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };